version: '3.8'

volumes:
  mysql-volume:

services:
  frontend:
    image: node:lts
    container_name: frontend
    ports:
      - ${FRONTEND_PORT}:8080
    volumes:
      - ./:/src
    working_dir: "/src/vuejs"
    tty: true

  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./laravel/:/var/www/html
  
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${BACKEND_PORT}:80
    depends_on:
      - backend
    volumes:
      - ./laravel/:/var/www/html

  database:
    build: ./docker/db
    platform: linux/x86_64
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rentalApp_db
      TZ: "Asia/Tokyo"
    ports:
      - ${DB_PORT}:3306