import Head from 'next/head'
import axios from "axios";
import { useState, useEffect } from 'react';
import Link from 'next/link';

export async function getServerSideProps() {
  
  const res = await axios.get("http://nginx:80/api/items", {
  });
  const data = await res.data;

  return { 
      props: {
          data: data 
      }
  };
}


const Home = ({ data }) => {
  data.items.map((d)=> {
    if(d.status === 0){
        d.status = "貸出可"
    }
    else if(d.status === 1){
        d.status = "貸出中"
    }
  });

  const [rental, setrental] = useState([]);
  useEffect(() => {
    axios.get('http://localhost:8000/api/rentalList')
    .then((res) => {
      setrental(res.data)
    })
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main>
        ALL ITEM LIST<br/><br/>
        <Link href={"/admin"}>管理者HOMEへ</Link><hr/>
     <div>
        {data.items.map((d) => (
        <ul key={d.id}>
            タイトル：{d.title}<br/><br/>貸出状況：{d.status}<br/><br/>借りている人：{rental.name}<br/><br/>借りた日：<br/><br/>返却日:<br/><br/><hr/>
        </ul>
        ))}
    </div>
      </main> 
    </div>
  )
}

export default Home 